### PR TITLE
fix: scroll to main thread post on page load

### LINKED ISSUE #2555: Threads should scroll down to the given post
When opening a thread it should open the main post first and threads above

Eg: https://lenster.xyz/posts/0x06-0x0188

It should open the page like this

Image

And not like this

Image

<sub>[ENG-43](https://linear.app/heyxyz/issue/ENG-43/threads-are-not-properly-shown)</sub>

### PR DESCRIPTION
**Pull request by SSHari**
## What does this PR do?

Adds functionality to scroll to the main thread post on page load.

This is a second attempt at fixing this issue after https://github.com/heyxyz/hey/pull/3909 was closed. In case this PR doesn't properly handle every edge case, I'm happy to address any issues instead of closing it.

## Related issues

Fixes #2555 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Explanation of the changes

The PR adds a few refs so we can access the height of different parts of the page (e.g. thread section, main post, and profile section). With that information, we can increase the `height` property of the main section to include additional space to accommodate placing the main post at the top of the page.

Once we have the additional space, we can scroll the main post into view which will place it at the top of the page. If the publication type is just a `Post`, we're skipping the scroll because there are no additional sections above the content.

/claim #2555

### CODE REVIEW

**Comment by SSHari** [comment]
I tried the changes with the following posts:
1. https://web-git-fork-sshari-patch-2555-heyxyz.vercel.app/posts/0x01bdb5-0x0801
2. https://web-git-fork-sshari-patch-2555-heyxyz.vercel.app/posts/0x01bbee-0x1881
3. https://web-git-fork-sshari-patch-2555-heyxyz.vercel.app/posts/0x73b1-0x36b2
4. https://web-git-fork-sshari-patch-2555-heyxyz.vercel.app/posts/0x01bdb5-0x07fa

It might be helpful to try the changes with other posts that are set up differently if possible.

**Comment by bigint** [comment]
doesnt work here

https://web-git-fork-sshari-patch-2555-heyxyz.vercel.app/posts/0x73b1-0x36b2

https://github.com/heyxyz/hey/assets/69431456/52817866-a283-4b4c-9e1f-01b7dc3b8e88

And breaks on all mobile screens

**Comment by SSHari** [comment]
@bigint I made some changes that I think should address the issues with https://web-git-fork-sshari-patch-2555-heyxyz.vercel.app/posts/0x73b1-0x36b2. It looks like this had to do with the `img` tags resizing after they fully loaded. Also, I've updated the logic to scroll when navigating between posts as well.

You also mentioned that the changes break on all mobile screens. Can you expand on what you mean or would you be able to share a video that shows what you're seeing? I'm trying the links on my own phone and things seem to be working as expected.

**Comment by bigint** [comment]
IMO the approach will be like load the publication first and load + append its parent on the top second lazily, same as twitter does 🙇🏼

**Comment by SSHari** [comment]
@bigint Are you sure that's what Twitter is doing? If we take a look at the following as an example: https://twitter.com/PurGameStories/status/1713948970727112914, it looks like all the parent tweets are already loaded in the DOM. They're positioned absolute and then each comment is translated down the Y-axis. The parent container also seems to have a _calculated_ minimum height based on the children (i.e. the tweets in the thread). Finally, Twitter automatically scrolls the screen to the comment in question.


https://github.com/heyxyz/hey/assets/11434879/8853dac1-e21d-4b46-9c1c-fc1c8ad99ff7

**Comment by bigint** [comment]
Yes @SSHari you can check their network requests

**Pull request closed without merging**
