### PR TITLE
enhancement: Added Select Menu (#4246)

### LINKED ISSUE #4246: UI: Design select menu
https://tailwindui.com/components/application-ui/forms/select-menus

Props:

- options[]
  - title: ReactNode 
  - description: ReactNode
  - key: string
  - value: string
-  `...rest` of HTML select

### PR DESCRIPTION
**Pull request by aadarsh-nagrath**
## What does this PR do?

This pull request implements the requested UI design for the select menu as described in issue #4246

fixes #4246 
/claim #4246

## Type of change

- [ ] Enhancement (non-breaking small changes to existing functionality)

BEFORE
Screenshot 2023-12-18 000855
AFTER
Screenshot 2023-12-18 013231

### CODE REVIEW

**Comment by bigint** [comment]
Do you have all props mentioned in the issue?

**Comment by bigint** [comment]
Also make sure to reduce spacing a little bit, it looks huge now!

**Comment by bigint** [comment]
Fix PR title to follow conventional commits

**Comment by aadarsh-nagrath** [comment]
@bigint  Updated

**Comment by bigint** [comment]
Can you show demo with description as well, also trying all props like disabled, selected etc

also looks like spacing is very huge between two items!

**Comment by bigint** [comment]
Closing this in favor of https://github.com/heyxyz/hey/pull/4259

That PR is advanced compared to this 🙇🏼

**Pull request closed without merging**
