### PR TITLE
fix: cache fix for virtuoso (#4201)

### PR DESCRIPTION
**Pull request by RutamBhagat**
## What does this PR do?
Fixes issue #4201 by caching user profiles

## Related issues

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Explanation of the changes
/claim #4201

https://github.com/heyxyz/hey/assets/72187009/4593240a-438a-4fdb-a3fd-8fe951fd568e

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@RutamBhagat I didn't know that this can be done. A learning!

**Comment by bigint** [comment]
It is not intended to see cache requests in network too, if you see twitter they do virtual scroll nicely 🤔

**Comment by bigint** [comment]
https://github.com/heyxyz/hey/assets/69431456/1138dd64-e467-428b-9db5-530356a6eb4e

**Comment by bigint** [comment]
Uploading Screen Recording 2023-12-13 at 11.28.39 AM.mov…

they unmount too

**Comment by rishi-raj-jain** [comment]
Damn 🤯

**Comment by bigint** [comment]
Twitter is always a engineering marvel lol 😅

**Comment by rishi-raj-jain** [comment]
> Screen.Recording.2023-12-13.at.11.30.31.AM.mov 
> they unmount too

Can you look into the tags they've used? are we sure they are loading images and not buffers?

**Comment by rishi-raj-jain** [comment]
Oh no they are also refetching

**Comment by rishi-raj-jain** [comment]
here goes 👇🏻

https://github.com/heyxyz/hey/assets/46300090/023c0cc7-b2ef-41c0-94d6-8944707a8cd0

**Comment by bigint** [comment]
@rishi-raj-jain @RutamBhagat this happens only if you disable cache on dev tools! if you disable it will not be called again!

**Comment by bigint** [comment]
If its something related to disk cache we don't want to do any code changes, it can be easily done on network layer!

**Comment by bigint** [comment]
Will react memo fix it?

**Comment by RutamBhagat** [comment]
> @rishi-raj-jain @RutamBhagat this happens only if you disable cache on dev tools! if you disable it will not be called again!

I am sorry, I am a bit confused, when I disable caching on twitter it still tries to refetch the images 


https://github.com/heyxyz/hey/assets/72187009/27b2e37c-71e3-4aec-b6fb-68b9a4f42776

**Comment by RutamBhagat** [comment]
> Will react memo fix it?

No it still shows that the request is cached in the networks tab but I feel like React.memo is a cleaner implementation

https://github.com/heyxyz/hey/assets/72187009/a3dc8199-d672-4aaa-a0a3-21fb11fb7048

**Comment by bigint** [comment]
Request is cached because we added cache headers on firewall!

**Comment by bigint** [comment]
Closing this, we can move discussion to issue!

**Pull request closed without merging**
