### PR TITLE
❇️ Fix: Efficient Image Format + Height and Width of icons

### PR DESCRIPTION
**Pull request by nermalcat69**
## What does this PR do?
usage of webp

## Related issues

Fixes
Just a a better format instead of png
## Type of change
- [ ] Png to Webp

- ati.png (189kb) -> ati.webp (27kb)
- logo.png (59kb) -> logo.webp (12kb)
- pride.png (25kb) -> pride.webp (12kb)
- icon-128x128.png (16kb) -> icon-128x128.webp (4kb)
- icon-512x512.png (189kb) -> icon-512x512.webp (27kb)
- icon-16x16.png (1kb) -> icon-16x16.webp (722bytes)
- icon-32x32.png (2kb) -> icon-32x32.webp (852bytes)

## Explanation of the changes
webps are more efficient as compared to png also the pr i did before was perfect, u just didnt check it carefully

### CODE REVIEW

**Comment by nermalcat69** [comment]
damn i think i need to fix this build error

**Comment by nermalcat69** [comment]
just checking, when i ran it locally... it clearly mentioned it made some pages 40% faster and stuff... + i added it to handle the dom elements efficiently... still testing (this pr is draft) dont close it , i'll try to fix # 4029 issue if i can 🙇🏼‍♂️

**Comment by nermalcat69** [comment]
as its failing here, i need to fix it 👍🏼

**Comment by nermalcat69** [comment]
i am thinking of implementing csr or maybe work around with the loader maybe.

**Comment by nermalcat69** [comment]
also this article about millionjs:  [https://andreassujono.medium.com/react-virtual-dom-is-slow-try-million-js-105474a93db6](https://andreassujono.medium.com/react-virtual-dom-is-slow-try-million-js-105474a93db6)

**Comment by bigint** [comment]
PS: @nermalcat69 this PR will not be eligible for bounty FYI!

if its really increasing the webvitals score we can tip some!

**Comment by bigint** [comment]
Any updates @nermalcat69?

**Comment by nermalcat69** [comment]
Hey @bigint kind of busy with some other stuff, i can close this if its irritating your eyes.. i'll open a new one later then :3

**Pull request closed without merging**
