### PR TITLE
fix: add proper cors validation on api and allow specific endpoints

### PR DESCRIPTION
**Pull request by Ameer-officials**
/claim #4155

## Related issues

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by Ameer-officials** [comment]
@bigint Ready for your review.

**Comment by bigint** [comment]
Have you tested this?

**Comment by Ameer-officials** [comment]
the test results as follows

Screenshot 2023-12-12 215037

**Comment by bigint** [comment]
I mean have you tested this implementation specifically?

**Comment by Ameer-officials** [comment]
yes , through postman but only from localhost.
Is there any specific you want me to do

**Comment by bigint** [comment]
https://github.com/heyxyz/hey/issues/4155#issuecomment-1855343284

**Pull request closed without merging**
