### PR TITLE
feat: switches to Smart Polls

### PR DESCRIPTION
**Pull request by iPaulPro**
## What does this PR do?

Switches to using [EASPollActionModule](https://github.com/iPaulPro/smart-polls) for polls.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by iPaulPro** [comment]
This is very out of date because it was started well-over a month ago but I'm still waiting on the Open Action to be verified.

One thing missing from this PR, is to use optimistic status for the votes. I'm happy to add that, but didn't want to keep working on it if the action will not be verified in its current state.

**Comment by bigint** [comment]
Hey I think we can move RPC calls to FE rather than using API

**Comment by bigint** [comment]
Also I just invited to the repo so you can create branch here and contribute, I see lot of conflicts already 😅

**Comment by iPaulPro** [comment]
Just a couple updates: EAS isn't yet deployed on Amoy, and I'm still waiting on the poll module to be verified before I continue more work on this PR.

**Comment by iPaulPro** [comment]
This seems like a waste of time since we don't know if EAS will ever launch on Lens Network.

**Pull request closed without merging**
