### PR TITLE
fix: cooldown message

### LINKED ISSUE #3800: [ENG-256] Cooldown status message issues
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sentence ending without value:
"Your profile protection disabling has been triggered. It will take effect in"

https://github.com/lensterxyz/lenster/assets/667227/5e2b45ac-6930-43c0-a6b4-f7bba1231dbe

When refreshing the page, the message has strange grammar: "Your profile protection disabled."

Screenshot_2023-09-18_17-34-14

### Expected Behavior

When timing has ended, the message should change to
"Your profile protection is disabled."

### Steps To Reproduce

- Go to https://lenster.xyz/settings/danger > Disable profile guardian
- Click **Disable now**
- Refresh page

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

_No response_

<sub>[ENG-256](https://linear.app/heyxyz/issue/ENG-256)</sub>

### LINKED ISSUE #3801: [ENG-257] Cooldown logic
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On https://lenster.xyz/settings/danger
the text says "A 7-day Security Cooldown Period need to be elapsed for the Profile Guardian to become effectively disabled."
But then, the time seems to actually be 5 minutes, and not 7 days.

Screenshot_2023-09-18_17-28-01

Screenshot_2023-09-18_17-36-26

### Expected Behavior

Value in message should match the actual value used

### Steps To Reproduce

- Go to https://lenster.xyz/settings/danger > Disable profile guardian
- Observe the message
- Click **Disable now**
- Refresh page
- Observe the cooldown time

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

there is also some very strange logic in apps/web/src/components/Shared/ProtectProfile.tsx

```
  const coolOffDate =
    profileGuardianInformation.disablingProtectionTimestamp as any;
  const coolOffTime = new Date(
    new Date(coolOffDate).getTime() + 5 * 60 * 100
  ).toISOString();
  const isCoolOffPassed = new Date(coolOffDate).getTime() < Date.now();
```
The disablingProtectionTimestamp seems to come from the API and already contain the 5 additional minutes.
Then we do some math (`new Date(coolOffDate).getTime() + 5 * 60 * 100`) which is very strange, because getTime() returns milliseconds, so if anything, it should multiply by 1000. The effect is that it adds 30 seconds (one tenth of 5 minutes), so the resulting cooldown is 5m 30s. Although, this logic is superfluous anyway, since the 5 minutes are already included in disablingProtectionTimestamp.

<sub>[ENG-257](https://linear.app/heyxyz/issue/ENG-257)</sub>

### PR DESCRIPTION
**Pull request by Clueed**
## What does this PR do?

This PR fixes typos, countdown logic, and countdown display related to the profile guardian mechanic.

## Related issues

Fixes #3800
Fixes #3801 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### <samp>🤖 Generated by Copilot at bad0361</samp>

*  Update the text and countdown timer in the `GuardianSettings` and `ProtectProfile` components to reflect the new security cooldown period of 5 minutes ([link](https://github.com/heyxyz/hey/pull/3899/files?diff=unified&w=0#diff-7c93d329c665824b282d39c9a9a417223094b14938f2f1e27a541666a4c7b11fL84-R85), [link](https://github.com/heyxyz/hey/pull/3899/files?diff=unified&w=0#diff-6958c1c8be1cc974484a9cb8ecd88982088cc93561d62448760477d83f845056L78-R79))
*  Refactor and simplify the code in the `ProtectProfile` component to use destructuring assignment, optional chaining, and direct access to the `disablingProtectionTimestamp` property ([link](https://github.com/heyxyz/hey/pull/3899/files?diff=unified&w=0#diff-6958c1c8be1cc974484a9cb8ecd88982088cc93561d62448760477d83f845056L40-R48), [link](https://github.com/heyxyz/hey/pull/3899/files?diff=unified&w=0#diff-6958c1c8be1cc974484a9cb8ecd88982088cc93561d62448760477d83f845056L86-R86))
*  Modify the `CountdownTimer` component to display a zero second value and add spaces between the time units for readability ([link](https://github.com/heyxyz/hey/pull/3899/files?diff=unified&w=0#diff-212190824bab5d0a641018371f33df1d7417e2543c86a77d0d5a9b72dac71fd5L60-R70))
*  Correct the grammar and punctuation in the text of the `ProtectProfile` component ([link](https://github.com/heyxyz/hey/pull/3899/files?diff=unified&w=0#diff-6958c1c8be1cc974484a9cb8ecd88982088cc93561d62448760477d83f845056L64-R63), [link](https://github.com/heyxyz/hey/pull/3899/files?diff=unified&w=0#diff-6958c1c8be1cc974484a9cb8ecd88982088cc93561d62448760477d83f845056L78-R79))
*  Change the `ProfileGuardianInformationState` interface and the `setProfileGuardianInformation` function to use a union type for the `profileGuardianInformation` property, instead of optional or nullable types, to enforce the invariant and avoid type errors ([link](https://github.com/heyxyz/hey/pull/3899/files?diff=unified&w=0#diff-6fa155b9c76fca5bbee34fc39898d857e3b16083504888808e7c291f7bc7342dL3-R11), [link](https://github.com/heyxyz/hey/pull/3899/files?diff=unified&w=0#diff-6fa155b9c76fca5bbee34fc39898d857e3b16083504888808e7c291f7bc7342dL24-R25))

## Emoji

🚀🕒♻️

## Proof

Screenshot 2023-10-08 at 21 39 15

Screenshot 2023-10-08 at 21 42 46

### CODE REVIEW

**Comment by Clueed** [comment]
From my testing the API returns a date string like `Sun Oct 08 2023 21:15:03 GMT+0200 (Central European Summer Time)`. I've typed and made the component work with that.

**Comment by Clueed** [comment]
> It's 7 days, not 5 minutes, 5 minutes is only on testnet 🙇🏼 

Fixed in last commit.

**Comment by bigint** [comment]
We need to wait till https://github.com/heyxyz/hey/pull/3892/ goes out

**Review by foolo — COMMENTED** [review]
Looks OK to me, (although blocked by Lens v2 as for now)
Only thing that came to mind is  inconsistent wording:
There are three terms that describe the same thing "profile is unlocked", "profile protection disabled" and "profile guardian disabled".
For user experience, it's probably better to use one and the same term.

And a related minor thing, sometimes it's "Profile Guardian" capitalized, and sometimes "profile guardian".

**Comment by Clueed** [comment]
> Looks OK to me, (although blocked by Lens v2 as for now) Only thing that came to mind is inconsistent wording: There are three terms that describe the same thing "profile is unlocked", "profile protection disabled" and "profile guardian disabled". For user experience, it's probably better to use one and the same term.
> 
> And a related minor thing, sometimes it's "Profile Guardian" capitalized, and sometimes "profile guardian".

So, who decides what's the correct wording? I think it should be Profile Guardian because it's a specific feature of Lens protocol, but "your profile is locked" is clearer/more understandable.

**Comment by bigint** [comment]
@Clueed can you raise this against lens-v2 branch?

https://github.com/heyxyz/hey/pull/3914

**Comment by Clueed** [comment]
Sorry for the delay. I'm blocked by #3960: can't get it to run locally.

**Pull request closed without merging**
