### PR TITLE
fix: spotiy.link rich oembed

### LINKED ISSUE #3207: Fix spotify.link rich oembed
https://lenster.xyz/posts/0x73b1-0x2a23

<sub>[ENG-14](https://linear.app/heyxyz/issue/ENG-14/fix-spotifylink-rich-oembed)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
### <samp>🤖 Generated by Copilot at 465c309</samp>

Added support for Spotify short links in oembed worker. Modified `generateIframe` function and `knownSites` array in `packages/workers/oembed/src/helper/meta/generateIframe.ts` to handle the new site format.

## Related issues

Fixes #3207 
/claim #3207

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### <samp>🤖 Generated by Copilot at 465c309</samp>

*  Add support for generating iframe embeds for Spotify short links ([link](https://github.com/heyxyz/hey/pull/3872/files?diff=unified&w=0#diff-3fc76e1e5580e311391a78eb913f9112f6c6f55a2d97f5ea2f225f535e013167R6), [link](https://github.com/heyxyz/hey/pull/3872/files?diff=unified&w=0#diff-3fc76e1e5580e311391a78eb913f9112f6c6f55a2d97f5ea2f225f535e013167R17-R18), [link](https://github.com/heyxyz/hey/pull/3872/files?diff=unified&w=0#diff-3fc76e1e5580e311391a78eb913f9112f6c6f55a2d97f5ea2f225f535e013167R55-R61))

## Emoji

🎵🆕🖼️

### CODE REVIEW

**Comment by bigint** [comment]
@anikdhabal builds are failing, cuz you use the old fork 🙇🏼

**Comment by anikdhabal** [comment]
> @anikdhabal builds are failing, cuz you use the old fork 🙇🏼

Update it🙏

**Comment by bigint** [comment]
the thing is the url slug and the spotify embed link didn't match

**Comment by anikdhabal** [comment]
> the thing is the url slug and the spotify embed link didn't match

Yeah, the URL slug is not matching.

**Comment by bigint** [comment]
@anikdhabal any updates on this? or leave it to someone to pick this?

**Comment by anikdhabal** [comment]
> @anikdhabal any updates on this? or leave it to someone to pick this?

I will fix it by today.

**Comment by anikdhabal** [comment]
Also I'm getting some error at setup time .Could you provide a docs? @bigint

**Comment by anikdhabal** [comment]
@bigint I am getting few errors at the time setup. Can you provide docs to setup or guide?

**Comment by bigint** [comment]
Closing this for now 🙇🏼 When installations docs are there, we can reopen

**Comment by anikdhabal** [comment]
> Closing this for now 🙇🏼 When installations docs are there, we can reopen

Yeah, That would be better. Thank you.

**Pull request closed without merging**
