### PR TITLE
fix: error on switch profile

### LINKED ISSUE #3970: Fix error on switch profile to auto prompt wallet if logged out or incorrect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

Profile menu > Switch profile

### Expected Behavior

Should show profile list for switching

### Current Behavior

Error message:

> Failed to load profiles
> Response not successful: Received status code 400

Screenshot_2023-11-07_13-38-31

https://github.com/heyxyz/hey/assets/69431456/a199da37-e401-47a2-a3d5-f6dcadd46ff1

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### PR DESCRIPTION
**Pull request by nermalcat69**
## What does this PR do?
asks user to reconnect the wallet by saying "Wallet disconnected. Please reconnect your wallet"

## Related issues

/Fixes #3970 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Explanation of the changes
not needed

### CODE REVIEW

**Comment by nermalcat69** [comment]
Hey @bigint , I'm really not sure if this is what u needed. If this is not what u need please elaborate what u need to be done 💯 😸

**Comment by bigint** [comment]
@nermalcat69 this actually needs to prompt user to switch the wallet

**Comment by nermalcat69** [comment]
Sure!!

**Comment by nermalcat69** [comment]
Yes!!! just got on the pc

**Comment by nermalcat69** [comment]
also @bigint i would love to talk to you in discord dms

**Comment by nermalcat69** [comment]
i cant seem to reproduce this locally sadly + i wanted to work on the ui/ux issue about redesigning the new composer but i cant see to preview it i tried going to hey's discord but cant seem to find anyone who can help me with it.. so if i can get ur discord username or a server link i would love to get help on this as there is a waitlist. 👾

**Comment by bigint** [comment]
Closing this!

**Pull request closed without merging**
