### PR TITLE
fix: iframe size issues on mobile

### LINKED ISSUE #3949: Youtube issues with embed on mobile
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Youtube embed does not scale correctly

### Expected Behavior

Youtube should scale correctly

### Steps To Reproduce

Visit a post with youtube video on mobile

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Others

### Anything else?

Video of behavior https://hey.xyz/posts/0x0182d8-0x0126

### PR DESCRIPTION
**Pull request by Jaimin25**
## What does this PR do?
This will fix UI break cause of iframes in embed on mobile devices.

## Related issues

Fixes #3949 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Explanation of the changes
The iframes are in 16:9 ratio and also changed the player component width to full to slightly increase the size of the iframes.

https://github.com/heyxyz/hey/assets/65119631/5a0abfcf-dd80-4982-aad1-342219d9bf57

### CODE REVIEW

**Comment by bigint** [comment]
it still uses fixed width seems!

**Review by bigint — CHANGES_REQUESTED** [review]
dropped a comment!

**Comment by Jaimin25** [comment]
done! maybe inline styling won't work, and i guess [this](https://github.com/heyxyz/hey/blob/841211b63b112d9460193a324b87cb989f79ad29/apps/api/src/utils/oembed/meta/generateIframe.ts#L29C9-L29C23) wouldn't be required if the same properties are already defined in the CSS file. Should I remove it and make changes accordingly.

image



> dropped a comment!

**Comment by bigint** [comment]
It broke the ui for this

https://web-git-fork-jaimin25-iframe-embed-heyxyz.vercel.app/posts/0x0d-0x0424-DA-df8905b6

**Comment by bigint** [comment]
this is how it should looks like https://hey.xyz/posts/0x0d-0x0424-DA-df8905b6

**Comment by Jaimin25** [comment]
don't know why changes in generateIframe aren't visiting, on localhost it works fine

**Comment by Jaimin25** [comment]
> It broke the ui for this
> 
> https://web-git-fork-jaimin25-iframe-embed-heyxyz.vercel.app/posts/0x0d-0x0424-DA-df8905b6

works good now i think

image

image

**Comment by bigint** [comment]
Seems like bit complicated, i'll try to make PR on my own!

**Pull request closed without merging**
