### PR TITLE
feat: dockerize hey

### LINKED ISSUE #3896: Dockerization Proposal for heyxyz/hey
### Summary

**Proposal:**

I propose the Dockerization of the **heyxyz/hey** open-source project to enhance its accessibility, reproducibility, and deployment efficiency. Dockerization involves creating a Docker image and Docker Compose configurations that encapsulate the project's dependencies and environment settings.

**Benefits:**

**Simplified Setup:** Dockerization will streamline the setup process for newcomers and eliminate issues related to different development environments.

**Reproducibility:** With a Docker image, users can easily reproduce the project's environment, ensuring consistency across deployments.

**Portability:** Docker containers can run on various platforms, including local development machines, cloud servers, and CI/CD pipelines.

**Isolation:** Docker containers provide isolation, preventing conflicts with system-level dependencies.

**Discussion:** Initiate a discussion with the project maintainers and community members to finalize the Dockerization plan.

**Execution:** Execute the Dockerization process, following the defined plan and guidelines.

**Testing:** Thoroughly test the Docker image to ensure it functions as expected.

**Documentation Update:** Update the project's documentation to include Docker-related instructions.

**Announcement:** Announce the availability of the Dockerized version to the community and provide guidance on its usage.

### PR DESCRIPTION
**Pull request by ezhil56x**
## What does this PR do?
- This is to add Dockerization to hey

## Related issues

Fixes #3896 
/claim #3896 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Explanation of the changes
- Created a Dockerfile for web and api in the respective folders
- Docker images should be built first
- `pnpm docker:build-api` to build hey api docker image
- `pnpm docker:build-web` to build hey web docker image
- If required `docker-compose.yml` can be used

### CODE REVIEW

**Comment by ezhil56x** [comment]
I have verified that the passed env variables are accessible when I get into node runtime and check process.env but these are not getting used by the project

**Comment by bigint** [comment]
This is interesting issue, did you find solution for it?

**Comment by ezhil56x** [comment]
> This is interesting issue, did you find solution for it?

No, have tried my best, everything is being passed by not used by the project. Any suggestions on this

image

**Comment by bigint** [comment]
Closing this! feel free to open anytime 🙇🏼

**Comment by bangarisaiswaraj** [comment]
Hi @bigint
What happened with dockerisation. Please explain about the issue which made to close it here.

**Pull request closed without merging**
