### PR TITLE
(WIP) : Migrate composer to TipTap editor 

### LINKED ISSUE #4169: Migrate composer to TipTap editor
https://tiptap.dev/

We need to make sure the output should be in markdown also it need to support all existing plugins mainly the mentions

### PR DESCRIPTION
**Pull request by Rutik7066**
## NOTE: This is initial PR the work is in progress

Fixes #4169
/claim #4169 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by bigint** [comment]
make sure we need to remove lexical completely

**Comment by Rutik7066** [comment]
Sure

**Comment by Rutik7066** [comment]
Hi i want to discuss something about the issue can we continue on discord ?

**Comment by bigint** [comment]
Sure @Rutik7066

**Comment by Rutik7066** [comment]
Hey @bigint  I am closing this PR and reattempting the issue and make an PR..

**Comment by Rutik7066** [comment]
Hi @bigint Have you dropped this issue from bounty program ?

**Pull request closed without merging**
