### PR TITLE
fix doucment not find

### PR DESCRIPTION
**Pull request by xiaoyang886**
issue  'document is not find' when i execute script npm run dev in my mac

### CODE REVIEW

**Comment by xiaoyang886** [comment]
@bigint what wrong with this pr

**Comment by danimesq** [comment]
@xiaoyang886 how was you able to run Hey locally? Did it work getting and sending data?

**Comment by danimesq** [comment]
@xiaoyang886
How was you able to run Hey locally? Did it work getting and sending data?

**Comment by xiaoyang886** [comment]
> @xiaoyang886 How was you able to run Hey locally? Did it work getting and sending data?
work fine when i change code follow this pr

**Comment by xiaoyang886** [comment]
@danimesq work fine when i change code follow this pr

**Comment by danimesq** [comment]
> work fine when i change code follow this pr

@xiaoyang886 but you need to local environment variables right?
What APIs/RPCs you're running externally?

**Pull request closed without merging**
